# Generated by Django 2.2.4 on 2019-08-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjenzi_api', '0002_auto_20190827_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
    ]
