# Generated by Django 2.2.4 on 2019-08-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjenzi_api', '0003_remove_project_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailRecipients',
        ),
    ]
